// <auto-generated />
using System;
using CAS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CAS.Migrations
{
    [DbContext(typeof(CasContext))]
    [Migration("20260221045843_Tables")]
    partial class Tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CAS.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AppointmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Criticality")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ScheduleStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("AppointmentId")
                        .HasName("PK__Appointm__8ECDFCA25D4FAF2D");

                    b.HasIndex(new[] { "PatientId" }, "IDX_Appointment_PatientID");

                    b.ToTable("Appointment", (string)null);
                });

            modelBuilder.Entity("CAS.Models.Chemist", b =>
                {
                    b.Property<int>("ChemistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ChemistID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChemistId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ChemistName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ChemistStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ChemistId")
                        .HasName("PK__Chemist__C0D5B7B415F01C53");

                    b.ToTable("Chemist", (string)null);
                });

            modelBuilder.Entity("CAS.Models.Drug", b =>
                {
                    b.Property<int>("DrugId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DrugID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DrugId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Dosage")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DrugStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DrugTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("Expiry")
                        .HasColumnType("date");

                    b.HasKey("DrugId")
                        .HasName("PK__Drug__908D66F680539923");

                    b.ToTable("Drug", (string)null);
                });

            modelBuilder.Entity("CAS.Models.DrugRequest", b =>
                {
                    b.Property<int>("DrugRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DrugRequestID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DrugRequestId"));

                    b.Property<string>("DrugsInfoText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PhysicianId")
                        .HasColumnType("int")
                        .HasColumnName("PhysicianID");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime");

                    b.Property<string>("RequestStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("DrugRequestId")
                        .HasName("PK__DrugRequ__AEE9D650C71EAAC7");

                    b.HasIndex("PhysicianId");

                    b.ToTable("DrugRequest", (string)null);
                });

            modelBuilder.Entity("CAS.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("DOB");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PatientStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("PatientId")
                        .HasName("PK__Patient__970EC3464C9D9AEF");

                    b.ToTable("Patient", (string)null);
                });

            modelBuilder.Entity("CAS.Models.Physician", b =>
                {
                    b.Property<int>("PhysicianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PhysicianID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhysicianId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhysicianName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhysicianStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Specialization")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("PhysicianId")
                        .HasName("PK__Physicia__DFF5ED732E596253");

                    b.ToTable("Physician", (string)null);
                });

            modelBuilder.Entity("CAS.Models.PhysicianAdvice", b =>
                {
                    b.Property<int>("PhysicianAdviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PhysicianAdviceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhysicianAdviceId"));

                    b.Property<string>("Advice")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("ScheduleID");

                    b.HasKey("PhysicianAdviceId")
                        .HasName("PK__Physicia__82C626109A6A8F1D");

                    b.HasIndex("ScheduleId");

                    b.ToTable("PhysicianAdvice", (string)null);
                });

            modelBuilder.Entity("CAS.Models.PhysicianPrescrip", b =>
                {
                    b.Property<int>("PhysicianPrescripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PhysicianPrescripID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhysicianPrescripId"));

                    b.Property<string>("Dosage")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DrugId")
                        .HasColumnType("int")
                        .HasColumnName("DrugID");

                    b.Property<int>("PhysicianAdviceId")
                        .HasColumnType("int")
                        .HasColumnName("PhysicianAdviceID");

                    b.Property<string>("Prescription")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PhysicianPrescripId")
                        .HasName("PK__Physicia__DC5A5520ACB5FEBC");

                    b.HasIndex("PhysicianAdviceId");

                    b.HasIndex(new[] { "DrugId" }, "IDX_Prescrip_DrugID");

                    b.ToTable("PhysicianPrescrip", (string)null);
                });

            modelBuilder.Entity("CAS.Models.PurchaseOrderHeader", b =>
                {
                    b.Property<int>("Poid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("POID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Poid"));

                    b.Property<string>("PoStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Podate")
                        .HasColumnType("date")
                        .HasColumnName("PODate");

                    b.Property<string>("Pono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PONo");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("SupplierID");

                    b.HasKey("Poid")
                        .HasName("PK__Purchase__5F02A2F4491668DC");

                    b.HasIndex(new[] { "SupplierId" }, "IDX_PO_SupplierID");

                    b.HasIndex(new[] { "Pono" }, "UQ__Purchase__5F02AA86B0C286F3")
                        .IsUnique();

                    b.ToTable("PurchaseOrderHeader", (string)null);
                });

            modelBuilder.Entity("CAS.Models.PurchaseProductLine", b =>
                {
                    b.Property<int>("Ppid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PPID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ppid"));

                    b.Property<int>("DrugId")
                        .HasColumnType("int")
                        .HasColumnName("DrugID");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Poid")
                        .HasColumnType("int")
                        .HasColumnName("POID");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<int>("SlNo")
                        .HasColumnType("int");

                    b.HasKey("Ppid")
                        .HasName("PK__Purchase__5FD889CD19656513");

                    b.HasIndex("DrugId");

                    b.HasIndex(new[] { "Poid" }, "IDX_PPL_POID");

                    b.ToTable("PurchaseProductLine", (string)null);
                });

            modelBuilder.Entity("CAS.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ScheduleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("AppointmentID");

                    b.Property<int>("PhysicianId")
                        .HasColumnType("int")
                        .HasColumnName("PhysicianID");

                    b.Property<DateOnly>("ScheduleDate")
                        .HasColumnType("date");

                    b.Property<string>("ScheduleStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<TimeOnly>("ScheduleTime")
                        .HasColumnType("time");

                    b.HasKey("ScheduleId")
                        .HasName("PK__Schedule__9C8A5B69C14C1BA7");

                    b.HasIndex("AppointmentId");

                    b.HasIndex(new[] { "PhysicianId" }, "IDX_Schedule_PhysicianID");

                    b.ToTable("Schedule", (string)null);
                });

            modelBuilder.Entity("CAS.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SupplierID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SupplierStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("SupplierId")
                        .HasName("PK__Supplier__4BE666947104C895");

                    b.ToTable("Supplier", (string)null);
                });

            modelBuilder.Entity("CAS.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RoleReferenceId")
                        .HasColumnType("int")
                        .HasColumnName("RoleReferenceID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__User__1788CCAC1CB9B425");

                    b.HasIndex(new[] { "UserName" }, "UQ__User__C9F284565CF9C210")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("CAS.Models.Appointment", b =>
                {
                    b.HasOne("CAS.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_Appointment_Patient");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CAS.Models.DrugRequest", b =>
                {
                    b.HasOne("CAS.Models.Physician", "Physician")
                        .WithMany("DrugRequests")
                        .HasForeignKey("PhysicianId")
                        .IsRequired()
                        .HasConstraintName("FK_DrugRequest_Physician");

                    b.Navigation("Physician");
                });

            modelBuilder.Entity("CAS.Models.PhysicianAdvice", b =>
                {
                    b.HasOne("CAS.Models.Schedule", "Schedule")
                        .WithMany("PhysicianAdvices")
                        .HasForeignKey("ScheduleId")
                        .IsRequired()
                        .HasConstraintName("FK_PhysicianAdvice_Schedule");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("CAS.Models.PhysicianPrescrip", b =>
                {
                    b.HasOne("CAS.Models.Drug", "Drug")
                        .WithMany("PhysicianPrescrips")
                        .HasForeignKey("DrugId")
                        .IsRequired()
                        .HasConstraintName("FK_Prescrip_Drug");

                    b.HasOne("CAS.Models.PhysicianAdvice", "PhysicianAdvice")
                        .WithMany("PhysicianPrescrips")
                        .HasForeignKey("PhysicianAdviceId")
                        .IsRequired()
                        .HasConstraintName("FK_Prescrip_Advice");

                    b.Navigation("Drug");

                    b.Navigation("PhysicianAdvice");
                });

            modelBuilder.Entity("CAS.Models.PurchaseOrderHeader", b =>
                {
                    b.HasOne("CAS.Models.Supplier", "Supplier")
                        .WithMany("PurchaseOrderHeaders")
                        .HasForeignKey("SupplierId")
                        .IsRequired()
                        .HasConstraintName("FK_POHeader_Supplier");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("CAS.Models.PurchaseProductLine", b =>
                {
                    b.HasOne("CAS.Models.Drug", "Drug")
                        .WithMany("PurchaseProductLines")
                        .HasForeignKey("DrugId")
                        .IsRequired()
                        .HasConstraintName("FK_PPL_Drug");

                    b.HasOne("CAS.Models.PurchaseOrderHeader", "Po")
                        .WithMany("PurchaseProductLines")
                        .HasForeignKey("Poid")
                        .IsRequired()
                        .HasConstraintName("FK_PPL_PO");

                    b.Navigation("Drug");

                    b.Navigation("Po");
                });

            modelBuilder.Entity("CAS.Models.Schedule", b =>
                {
                    b.HasOne("CAS.Models.Appointment", "Appointment")
                        .WithMany("Schedules")
                        .HasForeignKey("AppointmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Schedule_Appointment");

                    b.HasOne("CAS.Models.Physician", "Physician")
                        .WithMany("Schedules")
                        .HasForeignKey("PhysicianId")
                        .IsRequired()
                        .HasConstraintName("FK_Schedule_Physician");

                    b.Navigation("Appointment");

                    b.Navigation("Physician");
                });

            modelBuilder.Entity("CAS.Models.Appointment", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("CAS.Models.Drug", b =>
                {
                    b.Navigation("PhysicianPrescrips");

                    b.Navigation("PurchaseProductLines");
                });

            modelBuilder.Entity("CAS.Models.Patient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("CAS.Models.Physician", b =>
                {
                    b.Navigation("DrugRequests");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("CAS.Models.PhysicianAdvice", b =>
                {
                    b.Navigation("PhysicianPrescrips");
                });

            modelBuilder.Entity("CAS.Models.PurchaseOrderHeader", b =>
                {
                    b.Navigation("PurchaseProductLines");
                });

            modelBuilder.Entity("CAS.Models.Schedule", b =>
                {
                    b.Navigation("PhysicianAdvices");
                });

            modelBuilder.Entity("CAS.Models.Supplier", b =>
                {
                    b.Navigation("PurchaseOrderHeaders");
                });
#pragma warning restore 612, 618
        }
    }
}
